<a href="https://colab.research.google.com/github/dhanushch18/Python-Full-Stack-with-Data-science/blob/main/numpy_ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
#NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so import

In [48]:
import numpy as np

In [49]:
list=[7,17,19]
list

[7, 17, 19]

In [50]:
np.array(list)

array([ 7, 17, 19])

In [51]:
my_matrix=[[7,17,18],[1,3,5],[2,4,6],[19,8,6],[9,99,999],[7,77,177]]
my_matrix

[[7, 17, 18], [1, 3, 5], [2, 4, 6], [19, 8, 6], [9, 99, 999], [7, 77, 177]]

In [52]:
np.array(my_matrix)

array([[  7,  17,  18],
       [  1,   3,   5],
       [  2,   4,   6],
       [ 19,   8,   6],
       [  9,  99, 999],
       [  7,  77, 177]])

Built-in Methods


There are lots of built-in ways to generate Arrays



```
`# This is formatted as code`
```



In [53]:
np.arange(1,18)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [54]:
#odd num.
np.arange(1,17,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [55]:
#even num.
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

zeros and ones


Generate arrays of zeros or ones

In [56]:
np.zeros(3)

array([0., 0., 0.])

In [57]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

linspace


Return evenly spaced numbers over a specified interval.

In [58]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [59]:
np.linspace(0,10,999)

array([ 0.        ,  0.01002004,  0.02004008,  0.03006012,  0.04008016,
        0.0501002 ,  0.06012024,  0.07014028,  0.08016032,  0.09018036,
        0.1002004 ,  0.11022044,  0.12024048,  0.13026052,  0.14028056,
        0.1503006 ,  0.16032064,  0.17034068,  0.18036072,  0.19038076,
        0.2004008 ,  0.21042084,  0.22044088,  0.23046092,  0.24048096,
        0.250501  ,  0.26052104,  0.27054108,  0.28056112,  0.29058116,
        0.3006012 ,  0.31062124,  0.32064128,  0.33066132,  0.34068136,
        0.3507014 ,  0.36072144,  0.37074148,  0.38076152,  0.39078156,
        0.4008016 ,  0.41082164,  0.42084168,  0.43086172,  0.44088176,
        0.4509018 ,  0.46092184,  0.47094188,  0.48096192,  0.49098196,
        0.501002  ,  0.51102204,  0.52104208,  0.53106212,  0.54108216,
        0.5511022 ,  0.56112224,  0.57114228,  0.58116232,  0.59118236,
        0.6012024 ,  0.61122244,  0.62124248,  0.63126253,  0.64128257,
        0.65130261,  0.66132265,  0.67134269,  0.68136273,  0.69

eye
Creates an identity matrix

In [60]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#Random
Numpy also has lots of ways to create random number arrays:

rand
### Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [61]:
np.random.rand(5)

array([0.10347392, 0.89185661, 0.77706847, 0.52322254, 0.85435469])

In [62]:
np.random.rand(4,4,2)

array([[[0.93858923, 0.77179821],
        [0.65749738, 0.26721825],
        [0.26951264, 0.45726023],
        [0.34907711, 0.96627954]],

       [[0.85852471, 0.1754524 ],
        [0.86227563, 0.78887824],
        [0.07615272, 0.52961097],
        [0.36193439, 0.04063189]],

       [[0.72765927, 0.10522025],
        [0.89297248, 0.40390567],
        [0.63934639, 0.89171227],
        [0.15179311, 0.82352532]],

       [[0.37540717, 0.71488527],
        [0.70158008, 0.47226393],
        [0.13524466, 0.5532705 ],
        [0.47822047, 0.2180342 ]]])

randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [63]:
np.random.randn(2)

array([-0.06383051,  1.20329175])

In [64]:
np.random.randn(5,5)

array([[ 0.22853827, -0.19541951, -0.0745118 , -0.19780306,  0.67960547],
       [ 0.04891031, -0.80294099,  0.81916904,  1.43326524, -0.06238183],
       [ 0.66273748,  0.55122527, -0.01165768,  0.05072615,  2.36444727],
       [-0.80271369, -0.96070114, -0.66662519, -0.05325987, -0.12992141],
       [ 0.71303076,  1.441989  , -0.37003071, -1.74005004,  0.36117474]])

randint
Return random integers from low (inclusive) to high (exclusive).



In [65]:
np.random.randint(1,100)

60

In [66]:
np.random.randint(1,50,10)

array([ 3, 33,  7, 26,  3, 26, 14, 20, 21, 19])

Array Attributes and Methods

In [67]:
arr = np.arange(25)
r=np.random.randint(2,50,10)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
r

array([13, 22, 44, 48, 23, 44, 14, 10, 31, 41])

Reshape


Returns an array containing the same data with a new shape.

In [70]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [71]:
r

array([13, 22, 44, 48, 23, 44, 14, 10, 31, 41])

In [72]:
r.max()

48

In [73]:
r.min()

10

In [74]:
r.argmax()

3

In [75]:
r.argmin()

7

Shape


Shape is an attribute that arrays have (not a method):

In [76]:
#vector
arr.shape

(25,)

In [77]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [78]:
arr.reshape(1,25).shape

(1, 25)

In [79]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [80]:
arr.reshape(25,1).shape

(25, 1)