<a href="https://colab.research.google.com/github/dhanushch18/Python-Full-Stack-with-Data-science/blob/main/Numpy001BASICS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
arr=np.array([x for x in range(1,10)])

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr1=np.array([x for x in range(1,13)])

In [13]:
arr1.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [15]:
arr1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
A=np.array([[1,2,3],[3,6,9]])
B=np.array([3,4,6])

In [18]:
A

array([[1, 2, 3],
       [3, 6, 9]])

In [19]:
B

array([3, 4, 6])

In [20]:
np.add(A,B)

array([[ 4,  6,  9],
       [ 6, 10, 15]])

In [22]:
np.subtract(A,B)

array([[-2, -2, -3],
       [ 0,  2,  3]])

In [23]:
np.multiply(A,B)

array([[ 3,  8, 18],
       [ 9, 24, 54]])

In [24]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.5       ],
       [1.        , 1.5       , 1.5       ]])

In [25]:
np.power(A,3)

array([[  1,   8,  27],
       [ 27, 216, 729]])

In [26]:
x=np.array([i for i in range(10)])

In [27]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.where(x%2==0,'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [29]:
condlist=[x<5,x>5]
choicelist=[x**2,x**3]

In [30]:
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])