<a href="https://colab.research.google.com/github/dhanushch18/Python-Full-Stack-with-Data-science/blob/main/Numpy_ds_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr=np.arange(1,10)

In [3]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
2/arr

array([2.        , 1.        , 0.66666667, 0.5       , 0.4       ,
       0.33333333, 0.28571429, 0.25      , 0.22222222])

In [9]:
arr **3

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

Universal Array Functions


Numpy comes with many universal array functions, which are essentially just mathematical operations you can use to perform the operation across the array.

In [10]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
np.exp(arr) #Calcualting exponential (e^)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [12]:
np.max(arr)

9

In [13]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [14]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])