<a href="https://colab.research.google.com/github/dhanushch18/Python-Full-Stack-with-Data-science/blob/main/Numpy_DS2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Indexing and Selection

In [41]:
import numpy as np

In [42]:
#Creating sample array

arr=np.arange(0,11)

In [43]:
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
#Get a value at an index
arr[-2]

9

In [45]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
array=arr[2:7]

In [48]:
array

array([2, 3, 4, 5, 6])

In [49]:
array[:]=7
array

array([7, 7, 7, 7, 7])

In [50]:
array

array([7, 7, 7, 7, 7])

In [51]:
arr

array([ 0,  1,  7,  7,  7,  7,  7,  7,  8,  9, 10])

In [52]:
arr_copy=arr.copy()
arr_copy

array([ 0,  1,  7,  7,  7,  7,  7,  7,  8,  9, 10])


Indexing a 2D array (matrices)

In [53]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
arr_2d[1]

array([20, 25, 30])

In [55]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][2]

30

In [56]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [57]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:



```
# This is formatted as code
```



In [58]:
arr2d=np.zeros((10,10))

In [59]:
#Length of array
arr_length = arr2d.shape[1]

In [60]:
for i in range(arr_length):
  arr2d[i]=i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [61]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

Selection


Let's briefly go over how to use brackets for selection based off of comparison operators.

In [62]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [64]:
bool_arr=arr>4

In [65]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True])

In [66]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [67]:
arr[arr>2]

array([3, 4, 5, 6, 7, 8, 9])

In [68]:
x=2
arr[arr>x]

array([3, 4, 5, 6, 7, 8, 9])

Great Job..!