<a href="https://colab.research.google.com/github/dhanushch18/Python-Full-Stack-with-Data-science/blob/main/Numpy003Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

In [19]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[5,6,7],[9,8,7],[1,2,3]])

In [20]:
arr1[0]

1

In [21]:
arr1

array([1, 2, 3, 4, 5, 6])

In [22]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr3

array([[5, 6, 7],
       [9, 8, 7],
       [1, 2, 3]])

In [24]:
arr2[-1]

array([4, 5, 6])

In [25]:
arr1[-3]

4

In [26]:
#slicing

In [27]:
arr1[1:]

array([2, 3, 4, 5, 6])

In [28]:
arr2[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr1[-3:-1]

array([4, 5])

In [30]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr2[1,1:]

array([5, 6])

In [32]:
arr2[0,1:]

array([2, 3])